//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Models", "FK_parentsearchable", "Unit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PTProject.Models.Unit), "Searchable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PTProject.Models.Searchable), true)]

#endregion

namespace PTProject.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PT_DB : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PT_DB object using the connection string found in the 'PT_DB' section of the application configuration file.
        /// </summary>
        public PT_DB() : base("name=PT_DB", "PT_DB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PT_DB object.
        /// </summary>
        public PT_DB(string connectionString) : base(connectionString, "PT_DB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PT_DB object.
        /// </summary>
        public PT_DB(EntityConnection connection) : base(connection, "PT_DB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Searchable> Searchables
        {
            get
            {
                if ((_Searchables == null))
                {
                    _Searchables = base.CreateObjectSet<Searchable>("Searchables");
                }
                return _Searchables;
            }
        }
        private ObjectSet<Searchable> _Searchables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Unit> Units
        {
            get
            {
                if ((_Units == null))
                {
                    _Units = base.CreateObjectSet<Unit>("Units");
                }
                return _Units;
            }
        }
        private ObjectSet<Unit> _Units;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Searchables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSearchables(Searchable searchable)
        {
            base.AddObject("Searchables", searchable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Units EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUnits(Unit unit)
        {
            base.AddObject("Units", unit);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Models", Name="Searchable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Searchable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Searchable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="content">Initial value of the content property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="unitId">Initial value of the unitId property.</param>
        public static Searchable CreateSearchable(global::System.Int32 id, global::System.String content, global::System.String type, global::System.String title, global::System.Int32 unitId)
        {
            Searchable searchable = new Searchable();
            searchable.Id = id;
            searchable.content = content;
            searchable.type = type;
            searchable.title = title;
            searchable.unitId = unitId;
            return searchable;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, false, "content");
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false, "type");
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false, "title");
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 unitId
        {
            get
            {
                return _unitId;
            }
            set
            {
                OnunitIdChanging(value);
                ReportPropertyChanging("unitId");
                _unitId = StructuralObject.SetValidValue(value, "unitId");
                ReportPropertyChanged("unitId");
                OnunitIdChanged();
            }
        }
        private global::System.Int32 _unitId;
        partial void OnunitIdChanging(global::System.Int32 value);
        partial void OnunitIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Models", "FK_parentsearchable", "Unit")]
        public Unit Unit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("Models.FK_parentsearchable", "Unit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("Models.FK_parentsearchable", "Unit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Unit> UnitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("Models.FK_parentsearchable", "Unit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Unit>("Models.FK_parentsearchable", "Unit", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Models", Name="Unit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Unit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Unit object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="usersId">Initial value of the usersId property.</param>
        public static Unit CreateUnit(global::System.Int32 id, global::System.String title, global::System.String type, global::System.String usersId)
        {
            Unit unit = new Unit();
            unit.Id = id;
            unit.title = title;
            unit.type = type;
            unit.usersId = usersId;
            return unit;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false, "title");
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false, "type");
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> unit_id
        {
            get
            {
                return _unit_id;
            }
            set
            {
                Onunit_idChanging(value);
                ReportPropertyChanging("unit_id");
                _unit_id = StructuralObject.SetValidValue(value, "unit_id");
                ReportPropertyChanged("unit_id");
                Onunit_idChanged();
            }
        }
        private Nullable<global::System.Int32> _unit_id;
        partial void Onunit_idChanging(Nullable<global::System.Int32> value);
        partial void Onunit_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> in_progress
        {
            get
            {
                return _in_progress;
            }
            set
            {
                Onin_progressChanging(value);
                ReportPropertyChanging("in_progress");
                _in_progress = StructuralObject.SetValidValue(value, "in_progress");
                ReportPropertyChanged("in_progress");
                Onin_progressChanged();
            }
        }
        private Nullable<global::System.Boolean> _in_progress;
        partial void Onin_progressChanging(Nullable<global::System.Boolean> value);
        partial void Onin_progressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> approved
        {
            get
            {
                return _approved;
            }
            set
            {
                OnapprovedChanging(value);
                ReportPropertyChanging("approved");
                _approved = StructuralObject.SetValidValue(value, "approved");
                ReportPropertyChanged("approved");
                OnapprovedChanged();
            }
        }
        private Nullable<global::System.Boolean> _approved;
        partial void OnapprovedChanging(Nullable<global::System.Boolean> value);
        partial void OnapprovedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usersId
        {
            get
            {
                return _usersId;
            }
            set
            {
                OnusersIdChanging(value);
                ReportPropertyChanging("usersId");
                _usersId = StructuralObject.SetValidValue(value, false, "usersId");
                ReportPropertyChanged("usersId");
                OnusersIdChanged();
            }
        }
        private global::System.String _usersId;
        partial void OnusersIdChanging(global::System.String value);
        partial void OnusersIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> can_be_searched
        {
            get
            {
                return _can_be_searched;
            }
            set
            {
                Oncan_be_searchedChanging(value);
                ReportPropertyChanging("can_be_searched");
                _can_be_searched = StructuralObject.SetValidValue(value, "can_be_searched");
                ReportPropertyChanged("can_be_searched");
                Oncan_be_searchedChanged();
            }
        }
        private Nullable<global::System.Boolean> _can_be_searched;
        partial void Oncan_be_searchedChanging(Nullable<global::System.Boolean> value);
        partial void Oncan_be_searchedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Models", "FK_parentsearchable", "Searchable")]
        public EntityCollection<Searchable> Searchables
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Searchable>("Models.FK_parentsearchable", "Searchable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Searchable>("Models.FK_parentsearchable", "Searchable", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
